### ISSUE TITLE
Nether portal dont break

### ISSUE THREAD

**Issue by SkyWaves123** [bergerhealer/MyWorlds#39] opened 2023-03-05 20:43 UTC
Upon players breaking the nether portal's frame, the portal remains intact. https://imgur.com/54TCFcK
I didnt know what plugin caused this but when i removed MyWorlds , the portal broke and the bug dissapeared.

**Comment by bergerkiller** [comment] 2023-03-05 21:02
There's a config.yml option to turn this off (overridePortalPhysics: false)

**Comment by SkyWaves123** [comment] 2023-03-06 20:24
this fixed my issue. tnx

**Comment by aml2023529** [comment] 2023-06-01 16:20
WIKI配置世界权限没了

**Comment by bbayu123** [comment] 2023-06-04 07:42
Closing issue, not a bug, workaround suggested.

**Closed by bbayu123** 2023-06-04 07:42 UTC
